### PR TITLE
Add trading UI features

### PR DESCRIPTION
**Pull request by KennethAshley**
# Why?
#29 

# What Changed?

Used Ant design with a combination of react to add ui trade elements

# Examples
image

## Gif
http://recordit.co/gU5R0VBnxh

### CODE REVIEW

**Comment by eswarasai** [comment]
@KennethAshley -- Thanks for the quick turnaround on this. I just have a couple of more suggestions :
- For Asks/Bids, instead of having a Radio button, is it possible to auto-load the values in the form, once a Table Row is clicked?
- I've observed that, on click of Buy/Sell, you're resetting both the form values irrespective of whether User has clicked Ok/Cancel

**Comment by KennethAshley** [comment]
@eswarasai I fixed the first issue. Can you explain the second one a bit more?

**Comment by eswarasai** [comment]
@KennethAshley -- Sure. Please find the steps below
1) Fill the form fields for both the Buy as well Sell
2) Click on either Buy or Sell button
3) Confirmation Modal pops up with Ok/Cancel button
4) In the background, you can see that the both the Buy as well as Sell form input fields are being reset

Suggested UX :
- Reset the fields of either Buy/Sell form only after the User clicks `Ok` in the confirmation modal

**Comment by KennethAshley** [comment]
@eswarasai check out the new code!

**Comment by eswarasai** [comment]
@KennethAshley -- Thanks for the quick turnaround. 

For some weird reason, the click on row of `Bids` Table is not updating the form fields of `Sell`. To reproduce, try to click through all the rows in the `Bids` Table and see the intermittent behaviour. Somehow, it's working fine for the `Asks` Table.

And also, if it isn't too much to ask, can you disable both the `Buy` and `Sell` button by default, enabling them only after passing the validations?

**Comment by KennethAshley** [comment]
@eswarasai ok! we should be good to go!!

**Pull request merged**
