### PR TITLE
Added styling for sample query list

### PR DESCRIPTION
**Pull request by KennethAshley**
# Why?

Current copy was a bit hard to read.

# What Changed?

- Reworked the `sampleQueries` array to include objects with `query` and `title`.
- Output the `sampleQueries` array to new `.sample-query-list` element.

# Example

image

### References
#43

### CODE REVIEW

**Comment by pelsasser** [comment]
@KennethAshley - see this screen shot - this breaks the other screens using different Data Sources

image

**Comment by KennethAshley** [comment]
@pelsasser I modified the `sampleQueries` to take an array of objects. Those objects have two properties. `query` and `title`.

**Comment by pelsasser** [comment]
@KennethAshley - any chance you can handle the needed changes so everything is back in a working state?

**Comment by KennethAshley** [comment]
@pelsasser yea for sure. Do we basically want to be able to swap `sampleQueries` out for other `sampleQueries`?

**Comment by pelsasser** [comment]
Not sure I follow what you are asking there

**Comment by eswarasai** [comment]
@pelsasser -- Looks good to me. I'm going ahead with merging this now.

**Pull request merged**
