### PR TITLE
Feature/9 show base token name and symbol

### PR DESCRIPTION
**Pull request by cryptomental**
This pull request solves #9 ,  Dapp shows now BASE_TOKEN name and symbol.

image

### CODE REVIEW

**Comment by eswarasai** [comment]
@cryptomental -- I have a suggestion here. Instead of having `search` icon for `BASE_TOKEN_SYMBOL`, maybe we can have a filter similar to `settled` with the available `symbols` as options. Let me know if you need any help with that. Thanks.

**Comment by cryptomental** [comment]
hi @eswarasai I will have a look.

**Comment by cryptomental** [comment]
@eswarasai could you please have a look now? I had a look at https://github.com/ant-design/ant-design/blob/master/components/table/demo/reset-filter.md and settled filter implementation and added this https://github.com/MarketProject/Dapp/pull/47/commits/c6adebb347b3d14de06a2fd5f6d82a791c4e9966

**Comment by cryptomental** [comment]
@eswarasai I forgot to mention, I can also squash last two commits if needed and my solution is acceptable.

**Comment by pelsasser** [comment]
@eswarasai let me know if you want me to take a look at any of this. finally catching up a bit

**Comment by cryptomental** [comment]
Hmm...I wanted to rebase and fix the conflict that appeared but it seems that a recent merge to master broke the explorer:

```
Found the Market Contract Registry at0xfb88de099e13c3ed21f80a7a1e49f8caecf10df6
:3000/static/js/bundle.js:180119 Found 5 contracts deployed
:3000/static/js/bundle.js:165283 Uncaught (in promise) Error: Cannot create instance of MarketCollateralPool; no code at address 0xf328c11c4df88d18fcbd30ad38d8b4714f4b33bf
```

@perfectmak @eswarasai could please have a look if you also see the same error?

I see this on master @ 29bcf08b4e7af8810d3e97645b61ea9c7d8ac7b5

**Comment by eswarasai** [comment]
@cryptomental -- I'll take a look at it and will try to fix the conflicts

**Comment by eswarasai** [comment]
@cryptomental -- This is the [commit](https://github.com/MarketProject/Dapp/commit/7b4d7f46add7b5a9b81ec1903832ddae91185cc1#diff-99701df44a591ac4cae0106d3b94c374) that has the conflicts with. As you can see, @perfectmak had created `src/Contracts.js` and he's importing from there.

So the only change that you need to be doing is that, `src/actions/explorer.js` should just have `import contract` statement which will fix the merge conflict. Once the rebase is done, you can add `CollateralToken` to `Contract.js` which should then be passed to `loadContracts` function in order to use it. Let me know if you need any help with this.

**Comment by cryptomental** [comment]
Hi @eswarasai thanks I did exactly the same steps to rebase locally ;) I will push this now. The problem though that I had yesterday was that master branch was broken.

**Comment by cryptomental** [comment]
Hmm I will double check coverage today.

**Comment by pelsasser** [comment]
@cryptomental - thanks - will get it merged once issues are fixed - let me know if you need any assistance

**Comment by cryptomental** [comment]
I will have a look at this again today afternoon, should not be too difficult to finish.

**Comment by cryptomental** [comment]
image

I got it right this time. Had to add CollateralToken export and modified explorer test. Slightly lower coverage is due to new lines added in places where we did not have any tests. I hope it is ready to be merged ;-) @eswarasai @pelsasser

**Comment by perfectmak** [comment]
Yeah, I think this can be merged now. Well done @cryptomental 🙂

**Comment by eswarasai** [comment]
@cryptomental -- Merging this now. Thanks for helping us getting this done :)

**Pull request merged**
