### PR TITLE
Improve test structure

### PR DESCRIPTION
**Pull request by arkgast**
The default configuration was ejected, now we can make any kind of configurations (we have the power).

The test code was refactored.

The structure was improved.

### CODE REVIEW

**Comment by eswarasai** [comment]
@arkgast -- Any specific reason why you've ejected the the `react-scripts`? What's the specific configuration you're looking for exactly that couldn't be done without ejecting them?

**Comment by arkgast** [comment]
Hi @eswarasai, well it was because there were a couple of configurations that were needed to setup in order to improve the test environment.

Look at the here:

img

As you can see the `setupTestFrameworkScriptFile` and `testMatch` options couldn't be overridden and those were necessary:

* To tell enzyme which adapter to use as is specified [here](http://airbnb.io/enzyme/).
* To Move the **test** folder outside the **src** folder.

**Comment by pelsasser** [comment]
@eswarasai - any further comments on this? are you good with me merging and releasing bounty?

**Comment by eswarasai** [comment]
@arkgast -- Got it. I'm unfamiliar with testing frameworks for React, but looks like `create-react-app` suggests `jest` as testing framework and it looks like you've chosen `enzyme`. Any particular reason for this?

PS: Ejecting the `react-scripts` makes it very difficult to upgrade the app in future and I'm assuming to maintain as well. So I'd really recommend not to `eject` the `react-scripts` and follow the standards that they've provided [here](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#running-tests).

**Comment by arkgast** [comment]
The project is using jest but also is using enzyme, enzyme is an utilitary to make easier to manipulate react components.

Maybe (maybe) will be a little bit harder to upgrade some packages in the future but believe me in some point you'll be forced to eject the default configuration because it's very limited.
With the default configuration you can't customize: jest, babel, webpack as you know react apps are based on those guys, so if you want to bring your app to the next level you need to play with all of them.

**Comment by eswarasai** [comment]
@arkgast -- Alright. I'll take your word for it 👍 
@pelsasser -- Please go ahead with the merge

**Pull request merged**
