### PR TITLE
Create UI elements for Wallet

### PR DESCRIPTION
**Pull request by KennethAshley**
# Why?

#30 

# What Changed?

Adds Tabpane, Table header and Table

# Example
asmtacdjg0

### CODE REVIEW

**Comment by eswarasai** [comment]
@KennethAshley -- Thanks for the quick turnaround on this one too. I have couple of suggestions (sorry for not adding them as part of initial requirements) :
- Remove the extra side tabs for Deposit/Withdraw ETH. We'd only need these 2 features. So you can replicate the same design as Buy/Sell Order Form
- Remove the Slider and the Time selection above the `Transactions` Table which isn't required

@pelsasser -- Do you have anything to add here?

Let us know once these are done. We're good to close the issue 👍

**Comment by KennethAshley** [comment]
@eswarasai Made the changes, does this look right? 

screencapture-localhost-3000-exchange-wallet-1518373263264

**Comment by eswarasai** [comment]
@KennethAshley -- Sorry about not being clear enough earlier. I've requested for the below changes :
- Deposit/Withdraw ETH are the 2 forms that are required. You can remove the Send ETX/ETH
- Deposit/Withdraw forms will be side by side similar to that of Buy/Sell Order form in Trades UI. So that you can remove the additional Tabs layout for Deposit/Withdraw

Let me know if you've any questions related to the above suggested changes. Thanks.

**Comment by KennethAshley** [comment]
@eswarasai No problem. Here is what i have now. I also am on your slack so we can communicate there in the future to not pollute the github thread. But check this out!

screencapture-localhost-3000-exchange-wallet-1518376734249

**Comment by eswarasai** [comment]
@KennethAshley -- Cool. Going forward we can communicate over Slack.
This looks perfect. Please commit your changes so that I can verify them on my end and close this issue. Thanks for your patience and hard work :)

**Comment by KennethAshley** [comment]
@eswarasai committed! but i can't 'submit work' on gitcoin. Its just pending.

**Comment by pelsasser** [comment]
@eswarasai - ready to merge this?  @KennethAshley - where you able to get the `submit work` to function properly?  If not I can always clawback and pay directly to you address

**Comment by KennethAshley** [comment]
@pelsasser i wasn't able to get the submit work to go through. I got a member of Gitcoin to take a look. He also suggested just paying directly to an address.

**Comment by eswarasai** [comment]
@pelsasser -- I've merged this PR. 
So @owocki suggested to clawback funds and pay @KennethAshley directly over the Gitcoin Slack

**Comment by pelsasser** [comment]
@KennethAshley - can you slack / email me address and I can get that taken care of for you! Thanks @eswarasai and @owocki

**Comment by pelsasser** [comment]
sent + tip!! thanks for the patience @KennethAshley

**Pull request merged**
