### PR TITLE
Add travis-ci and fix tests.

### PR DESCRIPTION
**Pull request by arkgast**
In response to #6

### CODE REVIEW

**Comment by perfectmak** [comment]
Good job @arkgast.
A question though, why the tests in the existing `tests` directory instead of the `__test__`? Any specific reason?

**Comment by arkgast** [comment]
Thanks @perfectmak 
Well the tests in **test** directory are for truffle and the ones that are in **__test__** are for react.

**Comment by perfectmak** [comment]
Okay, I was just wary of `__`'s... perhaps we can rename the folder. Maybe something like `dappTest`.
Perhaps @pelsasser is okay with it?

**Comment by perfectmak** [comment]
Also @arkgast can you take a look at the `setupTests.js` in this PR and refactor your tests to use something similar to perform initializations like `Enzyme.configure({ adapter: new Adapter() });`.

**Comment by arkgast** [comment]
Thanks @perfectmak 
Well the tests in `test` directory are for truffle and the ones who are in `__test__` are for react.

**Comment by arkgast** [comment]
Would be good I used `__test__` as a recommendation but no problem with the rename.

Having just one setup for enzyme was my first option but the default `create-react-app` configuration doesn't allow to setup the dir of that file, first we need to `npm run eject`.

**Comment by pelsasser** [comment]
I think we should blow away the solidity tests for the time being.  We aren't using those contracts, and maybe never will.  If we choose to in the future we can always put them into a different repo and import them via an npm package like we are with `market-solidity` to keep things more seperated.

thoughts on this?

**Comment by arkgast** [comment]
Sounds good to me, in that way we could have just one directory `test`  to test react components.

**Comment by perfectmak** [comment]
Yes, sounds good too. Lets have one `test` directory.

**Comment by arkgast** [comment]
Let's change the name of test directory in the next pr, after the command `npm run eject` is executed. Finally all test are passing :muscle:

**Comment by pelsasser** [comment]
@arkgast - so you want me to merge this and you will create the directory structure changes after?

**Comment by arkgast** [comment]
Yeah @pelsasser that would be better, because next pr will have a lot of changes.

**Comment by pelsasser** [comment]
okay will merge!

**Pull request merged**
